/* MC68882 coprocessor interface registers: how the 68030 reaches the FPU.
 *
 * `MC68881/MC68882 User's Manual` §7.2, Figure 7-2 and Table 7-2.
 *
 * ## The FPU is not memory mapped; it is decoded out of CPU space
 *
 * "The FPCP chip select decode ... uses the MPU function codes (FC0-FC2), the
 * CPU space type field (A16-A19), and the Cp-ID field (A13-A15). The FPCP
 * decodes the address bits A0-A4 to determine the function." So reaching the
 * coprocessor takes four things and an ordinary address is none of them --
 * which is why `[030]` §7.4.3 says these cycles "can only be generated by the
 * MOVES instruction" outside the coprocessor protocol itself.
 *
 * The type field for coprocessor communications is **`0010`**, and this core
 * already has the neighbouring value: `0000` is the breakpoint acknowledge
 * `BKPT` runs. Same address space, different type field, entirely different
 * transaction.
 *
 * ## Three details that make a naive register file wrong
 *
 * **The select field has don't-care bits.** Table 7-2 gives `A4-A0` as patterns,
 * not values: `0000x` for the response CIR, and `100xx` for the operand -- a
 * 32-bit register occupying four byte addresses. Decoding all five bits
 * exactly would leave every odd address undecoded, and the odd addresses are
 * reachable.
 *
 * **A read of a write-only register returns all ones**, not zero: "read accesses
 * of a write-only register always return all ones". Zero is a legal value for
 * most of these registers, so the difference is between a driver seeing an
 * obvious no-answer and seeing a plausible one.
 *
 * **Two registers in the map are not implemented on this part.** The operation
 * word and operand address CIRs are "optionally implemented by a coprocessor
 * only if they are needed; since they are not used by the MC68881, they are not
 * implemented. Writes to these locations are ignored, and reads always return
 * all ones." They are in Figure 7-2 and they do not exist, which is exactly the
 * kind of thing a map transcribed without its footnote gets wrong.
 */

#ifndef APOLLO_CPU_M68882_AP_M68882_CIR_H
#define APOLLO_CPU_M68882_AP_M68882_CIR_H

#include <stdbool.h>
#include <stdint.h>

/* `[030]` §7.4.3's CPU space type field for coprocessor communications. */
#define AP_M68882_CPU_SPACE_TYPE 0x2u

/* Which coprocessor the cycle is addressed to, from A13-A15. The 68882 on a
 * DN3500 answers cpID 1, which is the convention for the first floating-point
 * coprocessor; cpID 0 is the MMU and is not generated by the coprocessor
 * interface at all. */
#define AP_M68882_DEFAULT_CPID 1u

typedef enum {
  AP_M68882_CIR_RESPONSE,            /* $00, 16-bit, read */
  AP_M68882_CIR_CONTROL,             /* $02, 16-bit, write */
  AP_M68882_CIR_SAVE,                /* $04, 16-bit, read */
  AP_M68882_CIR_RESTORE,             /* $06, 16-bit, read/write */
  AP_M68882_CIR_OPERATION_WORD,      /* $08, not implemented on this part */
  AP_M68882_CIR_COMMAND,             /* $0A, 16-bit, write */
  AP_M68882_CIR_CONDITION,           /* $0E, 16-bit, write */
  AP_M68882_CIR_OPERAND,             /* $10, 32-bit, read/write */
  AP_M68882_CIR_REGISTER_SELECT,     /* $14, 16-bit, read */
  AP_M68882_CIR_INSTRUCTION_ADDRESS, /* $18, 32-bit, write */
  AP_M68882_CIR_OPERAND_ADDRESS,     /* $1C, not implemented on this part */
  AP_M68882_CIR_RESERVED,            /* $0C and $16 */
  AP_M68882_CIR_NONE,                /* not a coprocessor cycle at all */
} ap_m68882_cir_t;

/* Decode A0-A4 into a register, by Table 7-2's *patterns* -- the low bits are
 * don't-cares for the wider registers. */
[[nodiscard]] ap_m68882_cir_t ap_m68882_cir_select(uint32_t address);

/* Whether the whole cycle is addressed to this coprocessor: CPU space, type
 * field `0010`, and a matching cpID. All three, because any one of them alone
 * matches a transaction meant for something else -- the breakpoint acknowledge
 * shares the function code, and another coprocessor shares the type field. */
[[nodiscard]] bool ap_m68882_cir_selected(uint8_t function_code,
                                          uint32_t address, unsigned cpid);

/* Table 7-2's width in bits: 16 or 32. */
[[nodiscard]] unsigned ap_m68882_cir_width(ap_m68882_cir_t cir);

/* Table 7-2's access type. `readable` is false for a write-only register, whose
 * reads "always return all ones"; `writable` is false for a read-only one,
 * whose writes "are ignored". */
[[nodiscard]] bool ap_m68882_cir_readable(ap_m68882_cir_t cir);
[[nodiscard]] bool ap_m68882_cir_writable(ap_m68882_cir_t cir);

/* Whether this part implements the register at all. False for the operation
 * word and operand address CIRs, which Table 7-2's footnote excludes: they are
 * in the map and absent from the silicon. */
[[nodiscard]] bool ap_m68882_cir_implemented(ap_m68882_cir_t cir);

/* What a read of `cir` yields when it cannot be answered -- a write-only
 * register, a reserved one or an unimplemented one. All ones, never zero:
 * "read accesses of a write-only register always return all ones", and zero is
 * a legal value for most of these so a driver could not tell it from data. */
[[nodiscard]] uint32_t ap_m68882_cir_unreadable_value(ap_m68882_cir_t cir);

#endif /* APOLLO_CPU_M68882_AP_M68882_CIR_H */
