/* MC68040 floating-point exceptions and data-type support, `[040]` §9.6-§9.8.
 * See the header for what this part does that the 68882 does not. */

#include <string.h>

#include "cpu/m68040/ap_m68040_fp_exception.h"

/* ---------------------------------------------------------------------------
 * Data formats and types, Table 9-2.
 * ------------------------------------------------------------------------- */

#define H AP_M68040_FP_HARDWARE
#define S AP_M68040_FP_SOFTWARE
#define X AP_M68040_FP_UNSUPPORTED

/* Rows are types, columns are formats, in the manual's order. Transcribed from
 * the page image: the extraction lost most of the marks. */
static const ap_m68040_fp_support_t
    support[AP_M68040_FP_TYPE_COUNT][AP_M68040_FP_FORMAT_COUNT] = {
        /*                  single dbl ext pkd byte word long */
        [AP_M68040_FP_NORMALIZED] = {H, H, H, S, H, H, H},
        [AP_M68040_FP_ZERO] = {H, H, H, S, H, H, H},
        [AP_M68040_FP_INFINITY] = {H, H, H, S, X, X, X},
        [AP_M68040_FP_NAN] = {H, H, H, S, X, X, X},
        /* Every cell software: the hardware handles no denormal at all. */
        [AP_M68040_FP_DENORMALIZED] = {S, S, S, S, X, X, X},
        /* Only the two formats with an explicit integer bit or a digit string
         * can represent one. */
        [AP_M68040_FP_UNNORMALIZED] = {X, X, S, S, X, X, X},
};

#undef H
#undef S
#undef X

ap_m68040_fp_support_t ap_m68040_fp_support(ap_m68040_fp_format_t format,
                                            ap_m68040_fp_type_t type) {
  if (format >= AP_M68040_FP_FORMAT_COUNT || type >= AP_M68040_FP_TYPE_COUNT) {
    return AP_M68040_FP_UNSUPPORTED;
  }
  return support[type][format];
}

bool ap_m68040_fp_operand_unsupported(ap_m68040_fp_format_t format,
                                      ap_m68040_fp_type_t type) {
  /* §9.6.2's rule, which is Table 9-2's software column read as a predicate:
   * "denormalized (for single-, double-, and extended-precision operands),
   * unnormalized (for extended-precision operands), or either the source or
   * destination data format is packed decimal real". A combination the table
   * leaves blank cannot arise as an operand and is not an exception. */
  return ap_m68040_fp_support(format, type) == AP_M68040_FP_SOFTWARE;
}

/* ---------------------------------------------------------------------------
 * Arithmetic exceptions, §9.7.
 * ------------------------------------------------------------------------- */

unsigned ap_m68040_fp_enable_bit(ap_m68040_fp_exception_t exception) {
  /* Bit 15 highest priority down to bit 8 lowest, which is the enumeration's
   * own order counted down from 15. */
  if (exception >= AP_M68040_FPEXC_COUNT) {
    return 0u;
  }
  return 15u - (unsigned)exception;
}

ap_m68040_fp_vector_t
ap_m68040_fp_exception_vector(ap_m68040_fp_exception_t exception) {
  /* Table 9-9. Note the two inexact classes share vector 49: §9.7.7, "only one
   * inexact exception vector number is generated by the processor". */
  static const ap_m68040_fp_vector_t vectors[AP_M68040_FPEXC_COUNT] = {
      [AP_M68040_FPEXC_BSUN] = AP_M68040_FPVEC_BSUN,
      [AP_M68040_FPEXC_SNAN] = AP_M68040_FPVEC_SNAN,
      [AP_M68040_FPEXC_OPERR] = AP_M68040_FPVEC_OPERR,
      [AP_M68040_FPEXC_OVFL] = AP_M68040_FPVEC_OVFL,
      [AP_M68040_FPEXC_UNFL] = AP_M68040_FPVEC_UNFL,
      [AP_M68040_FPEXC_DZ] = AP_M68040_FPVEC_DZ,
      [AP_M68040_FPEXC_INEX2] = AP_M68040_FPVEC_INEX,
      [AP_M68040_FPEXC_INEX1] = AP_M68040_FPVEC_INEX,
  };
  if (exception >= AP_M68040_FPEXC_COUNT) {
    return AP_M68040_FPVEC_BSUN;
  }
  return vectors[exception];
}

bool ap_m68040_fp_has_maskable(ap_m68040_fp_exception_t exception) {
  /* §9.7.4.1 and §9.7.5.1 both read "MASKABLE EXCEPTION CONDITIONS. There are
   * no conditions." Every other exception has maskable conditions. */
  return exception != AP_M68040_FPEXC_OVFL && exception != AP_M68040_FPEXC_UNFL;
}

bool ap_m68040_fp_has_nonmaskable(ap_m68040_fp_exception_t exception) {
  /* "The processor encounters a nonmaskable SNAN, OPERR, OVFL, and UNFL
   * condition", and §9.7.1.2 says of BSUN "NONMASKABLE EXCEPTION CONDITIONS.
   * There are no conditions." DZ, INEX2 and INEX1 are maskable only. */
  switch (exception) {
  case AP_M68040_FPEXC_SNAN:
  case AP_M68040_FPEXC_OPERR:
  case AP_M68040_FPEXC_OVFL:
  case AP_M68040_FPEXC_UNFL:
    return true;
  case AP_M68040_FPEXC_BSUN:
  case AP_M68040_FPEXC_DZ:
  case AP_M68040_FPEXC_INEX2:
  case AP_M68040_FPEXC_INEX1:
  case AP_M68040_FPEXC_COUNT:
    return false;
  }
  return false;
}

bool ap_m68040_fp_generated_in_hardware(ap_m68040_fp_exception_t exception) {
  /* "The MC68040 generates the first seven exceptions in hardware and the
   * eighth only in software", and §9.7 says why: with no packed decimal support
   * "the processor never sets INEX1 bit in the FPSR EXC byte, but provides it
   * as a latch so that emulation software can report the exception." */
  return exception < AP_M68040_FPEXC_INEX1;
}

/* ---------------------------------------------------------------------------
 * State frames, §9.8.
 * ------------------------------------------------------------------------- */

ap_m68040_fp_frame_t
ap_m68040_fp_save_frame(bool executed_nonconditional,
                        bool unimplemented_instruction,
                        bool unsupported_data_type) {
  /* "When an unimplemented floating-point exception occurs, the FSAVE generates
   * a 26-word unimplemented instruction state frame. When an unsupported data
   * type exception occurs, the FSAVE generates a 50-word busy state frame." */
  if (unimplemented_instruction) {
    return AP_M68040_FPFRAME_UNIMPLEMENTED;
  }
  if (unsupported_data_type) {
    return AP_M68040_FPFRAME_BUSY;
  }
  /* "An idle state frame is saved if no exceptions are pending and at least one
   * instruction has been executed since the last hardware reset or FRESTORE of
   * a null state frame" -- one *non-conditional* instruction, which is where
   * this part differs from the MC68881 and MC68882. */
  return executed_nonconditional ? AP_M68040_FPFRAME_IDLE
                                 : AP_M68040_FPFRAME_NULL;
}

bool ap_m68040_fp_is_conditional(const char *mnemonic) {
  /* "Conditionals include FNOP, FBcc, FDBcc, FScc, and FTRAPcc." */
  static const char *const conditionals[] = {"FNOP", "FBcc", "FDBcc", "FScc",
                                             "FTRAPcc"};
  if (mnemonic == NULL) {
    return false;
  }
  for (unsigned i = 0; i < sizeof conditionals / sizeof conditionals[0]; i++) {
    if (strcmp(conditionals[i], mnemonic) == 0) {
      return true;
    }
  }
  return false;
}
