/* MC68040 floating-point exceptions and data-type support: `[040]` §9.6-§9.8.
 *
 * `MC68040 User's Manual (1993)` §9, read whole (pp. 254-301).
 *
 * §9.2 is not modelled here and does not need to be: "the model ... is
 * identical to the programming model for the MC68881/MC68882 floating-point
 * coprocessors", and `cpu/m68882/ap_m68882_regs.h` already carries every bit of
 * it -- the `FPCR` enable and mode bytes, `PREC` and `RND`, the `FPSR`
 * condition code, quotient, exception and accrued bytes, and the `AEXC`
 * equations. Walking §9.2 against that header found no difference. What this
 * module carries is the part of §9 that is *not* the 68882.
 *
 * ## The hardware handles no denormalized number, in any format
 *
 * Table 9-2 crosses six number types against seven data formats and marks each
 * cell hardware, software or neither. Every denormalized cell is **software**,
 * in single, double, extended and packed alike; every packed-decimal cell is
 * software; unnormalized exists only for extended and packed and is software
 * there too. §9.6.2 states the rule the table implies: "an unsupported data type
 * exception occurs when either operand to an implemented floating-point
 * instruction is denormalized (for single-, double-, and extended-precision
 * operands), unnormalized (for extended-precision operands), or either the
 * source or destination data format is packed decimal real."
 *
 * So an FPU model that computes with a denormal in hardware diverges from the
 * part, which takes vector 55 and hands the operand to the `M68040FPSP`
 * instead. The 68882 this core models *does* handle denormals, which is exactly
 * why the difference has to be written down rather than inherited.
 *
 * Two qualifications from §9.4 and §9.6.2, both easy to get backwards:
 *
 *   - A denormalized operand is normalized before an *operation*, but "an
 *     external denormalized number **moved** into a floating-point data
 *     register is stored as a denormalized number". A move is not an operation.
 *   - "A denormalized value generated **as the result** of a floating-point
 *     operation generates a nonmaskable underflow exception instead of an
 *     unsupported data type exception." The data type exception is about
 *     *inputs*.
 *
 * ## Four exceptions are nonmaskable, and that is new
 *
 * §9.7 lists eight arithmetic exceptions in priority order and then gives each
 * one a *maskable* and a *nonmaskable* subsection, several of which read "there
 * are no conditions". The nonmaskable ones fire whatever the `FPCR` enable byte
 * says: "this allows a supervisor exception handler to correct a defaulting
 * result generated by the MC68040 that is different from the result generated
 * by an MC68881/MC68882 executing the same code." The 68882 has no such
 * concept -- an exception it does not enable is not taken -- so a model that
 * inherits the 68882's masking silently drops four trap classes.
 *
 * `OVFL` and `UNFL` are nonmaskable *only*: §9.7.4.1 and §9.7.5.1 both read
 * "there are no conditions" under MASKABLE. `BSUN` is the mirror image, with
 * §9.7.1.2's NONMASKABLE reading "there are no conditions".
 *
 * ## `INEX1` is a latch the hardware never sets
 *
 * §9.7: "Since the MC68040 does not directly support packed decimal real
 * operands, the processor never sets INEX1 bit in the FPSR EXC byte, but
 * provides it as a latch so that emulation software can report the exception."
 * One of the eight is software-only, and §9.7 says so in the same breath: "the
 * MC68040 generates the first seven exceptions in hardware and the eighth only
 * in software."
 *
 * ## An `FSAVE` after only conditional instructions differs from the 68882
 *
 * §9.8: the null state frame "is generated until the first nonconditional
 * floating-point instruction is executed (conditionals include FNOP, FBcc,
 * FDBcc, FScc, and FTRAPcc). Floating-point conditional instructions do not set
 * an internal flag, which changes the state frame from null to idle ... **Note
 * that this function is different from that of the MC68881 and MC68882**, and
 * software must be aware of this difference if compatibility ... is desired."
 * A program that resets, executes an `FBcc`, and saves gets a null frame here
 * and an idle frame on the earlier parts.
 */

#ifndef APOLLO_CPU_M68040_AP_M68040_FP_EXCEPTION_H
#define APOLLO_CPU_M68040_AP_M68040_FP_EXCEPTION_H

#include <stdbool.h>

/* ---------------------------------------------------------------------------
 * Data formats and types, Table 9-2.
 * ------------------------------------------------------------------------- */

typedef enum {
  AP_M68040_FP_SINGLE,
  AP_M68040_FP_DOUBLE,
  AP_M68040_FP_EXTENDED,
  AP_M68040_FP_PACKED,
  AP_M68040_FP_BYTE_INTEGER,
  AP_M68040_FP_WORD_INTEGER,
  AP_M68040_FP_LONG_INTEGER,
  AP_M68040_FP_FORMAT_COUNT
} ap_m68040_fp_format_t;

typedef enum {
  AP_M68040_FP_NORMALIZED,
  AP_M68040_FP_ZERO,
  AP_M68040_FP_INFINITY,
  AP_M68040_FP_NAN,
  AP_M68040_FP_DENORMALIZED,
  AP_M68040_FP_UNNORMALIZED,
  AP_M68040_FP_TYPE_COUNT
} ap_m68040_fp_type_t;

typedef enum {
  AP_M68040_FP_UNSUPPORTED, /* blank in Table 9-2: the combination does not
                             * exist -- an integer has no NAN */
  AP_M68040_FP_HARDWARE,    /* `*`, on-chip MC68040 FPU hardware */
  AP_M68040_FP_SOFTWARE     /* `+`, M68040FPSP */
} ap_m68040_fp_support_t;

[[nodiscard]] ap_m68040_fp_support_t
ap_m68040_fp_support(ap_m68040_fp_format_t format, ap_m68040_fp_type_t type);

/* Whether an *operand* of this format and type raises the unsupported data type
 * exception, §9.6.2. Not the same question as `ap_m68040_fp_support`: a
 * combination the table leaves blank cannot arise as an operand at all. */
[[nodiscard]] bool ap_m68040_fp_operand_unsupported(ap_m68040_fp_format_t format,
                                                    ap_m68040_fp_type_t type);

/* ---------------------------------------------------------------------------
 * Exception vectors, Table 9-9.
 * ------------------------------------------------------------------------- */

typedef enum {
  /* Shared with the F-line illegal instruction, which is why §9.6.1 says the
   * handler "uses the stack frame format ($0 or $2) to distinguish between the
   * two". */
  AP_M68040_FPVEC_UNIMPLEMENTED_INSTRUCTION = 11,
  AP_M68040_FPVEC_BSUN = 48,
  AP_M68040_FPVEC_INEX = 49,
  AP_M68040_FPVEC_DZ = 50,
  AP_M68040_FPVEC_UNFL = 51,
  AP_M68040_FPVEC_OPERR = 52,
  AP_M68040_FPVEC_OVFL = 53,
  AP_M68040_FPVEC_SNAN = 54,
  AP_M68040_FPVEC_UNIMPLEMENTED_DATA_TYPE = 55
} ap_m68040_fp_vector_t;

/* ---------------------------------------------------------------------------
 * Arithmetic exceptions, §9.7, in the priority order §9.7 lists them.
 * ------------------------------------------------------------------------- */

typedef enum {
  AP_M68040_FPEXC_BSUN, /* highest priority; FPCR enable bit 15 */
  AP_M68040_FPEXC_SNAN,
  AP_M68040_FPEXC_OPERR,
  AP_M68040_FPEXC_OVFL,
  AP_M68040_FPEXC_UNFL,
  AP_M68040_FPEXC_DZ,
  AP_M68040_FPEXC_INEX2,
  AP_M68040_FPEXC_INEX1, /* lowest priority; FPCR enable bit 8 */
  AP_M68040_FPEXC_COUNT
} ap_m68040_fp_exception_t;

/* "The bits of the ENABLE byte are organized in decreasing priority, with bit
 * 15 being the highest and bit 8 the lowest", so priority and bit position are
 * the same ordering read two ways. */
[[nodiscard]] unsigned
ap_m68040_fp_enable_bit(ap_m68040_fp_exception_t exception);

[[nodiscard]] ap_m68040_fp_vector_t
ap_m68040_fp_exception_vector(ap_m68040_fp_exception_t exception);

/* Whether the `FPCR` enable byte can cause this exception to be taken. */
[[nodiscard]] bool
ap_m68040_fp_has_maskable(ap_m68040_fp_exception_t exception);

/* Whether this exception is taken regardless of the `FPCR` enable byte -- the
 * concept the 68882 does not have. */
[[nodiscard]] bool
ap_m68040_fp_has_nonmaskable(ap_m68040_fp_exception_t exception);

/* "The MC68040 generates the first seven exceptions in hardware and the eighth
 * only in software." */
[[nodiscard]] bool
ap_m68040_fp_generated_in_hardware(ap_m68040_fp_exception_t exception);

/* ---------------------------------------------------------------------------
 * State frames, §9.8.
 * ------------------------------------------------------------------------- */

typedef enum {
  AP_M68040_FPFRAME_NULL,
  AP_M68040_FPFRAME_IDLE,
  AP_M68040_FPFRAME_UNIMPLEMENTED, /* 26 words */
  AP_M68040_FPFRAME_BUSY           /* 50 words */
} ap_m68040_fp_frame_t;

#define AP_M68040_FPFRAME_UNIMPLEMENTED_WORDS 26u
#define AP_M68040_FPFRAME_BUSY_WORDS 50u

/* Which frame an `FSAVE` produces. `executed_nonconditional` is whether any
 * non-conditional floating-point instruction has run since the last hardware
 * reset or `FRESTORE` of a null frame -- the flag §9.8 says the conditional
 * instructions do *not* set, and the point where this part parts company with
 * the MC68881 and MC68882. */
[[nodiscard]] ap_m68040_fp_frame_t
ap_m68040_fp_save_frame(bool executed_nonconditional,
                        bool unimplemented_instruction,
                        bool unsupported_data_type);

/* The five instructions §9.8 counts as conditional, which therefore leave a
 * reset FPU in the null state. */
[[nodiscard]] bool ap_m68040_fp_is_conditional(const char *mnemonic);

#endif /* APOLLO_CPU_M68040_AP_M68040_FP_EXCEPTION_H */
